### PR TITLE
Fix user domain list, improve role selection 

### LINKED ISSUE #81: On the domain users view role selector not possible to select GUEST role
image

### PR DESCRIPTION
**Pull request by kbeyro**

### CODE REVIEW

File: src/app/appmarket/users/list/userslist.component.ts [hunk 1]
```diff
@@ -79,6 +74,7 @@ export class UsersListComponent implements OnInit {
 
         users.subscribe((all) => {
             this.allUsers = all;
+            console.log(this.allUsers);
```
Comment (llopat) [inline src/app/appmarket/users/list/userslist.component.ts]: Do we still need this console log?

**Review by llopat — APPROVED** [review]
